import { ILevel } from "./interfaces";

export const levels: ILevel[] = [
    {
        itemSet: [
            { id: 1, color: "blue", order: 3, tube: 1, },
            { id: 2, color: "blue", order: 2, tube: 1, },
            { id: 3, color: "red", order: 1, tube: 1, },
            { id: 4, color: "red", order: 4, tube: 1, },
            { id: 5, color: "red", order: 3, tube: 2, },
            { id: 6, color: "red", order: 2, tube: 2, },
            { id: 7, color: "blue", order: 1, tube: 2, },
            { id: 8, color: "blue", order: 4, tube: 2, }
        ],
        colorCount: 2,
        tubeCount: 3
    },
    {
        tubeCount: 3,
        colorCount: 2,
        itemSet: [
            { id: 1, color: "red", tube: 1, order: 4 },
            { id: 2, color: "red", tube: 1, order: 2 },
            { id: 3, color: "red", tube: 2, order: 1 },
            { id: 4, color: "red", tube: 2, order: 3 },
            { id: 5, color: "green", tube: 1, order: 3 },
            { id: 6, color: "green", tube: 1, order: 1 },
            { id: 7, color: "green", tube: 2, order: 2 },
            { id: 8, color: "green", tube: 3, order: 1 },
        ],
    },
    {
        tubeCount: 5,
        colorCount: 3,
        itemSet: [
            { id: 1, color: "red", tube: 1, order: 3 },
            { id: 2, color: "red", tube: 2, order: 4 },
            { id: 3, color: "red", tube: 2, order: 3 },
            { id: 4, color: "red", tube: 3, order: 1 },
            { id: 5, color: "green", tube: 1, order: 1 },
            { id: 6, color: "green", tube: 2, order: 2 },
            { id: 7, color: "green", tube: 3, order: 3 },
            { id: 8, color: "green", tube: 3, order: 4 },
            { id: 9, color: "blue", tube: 1, order: 4 },
            { id: 10, color: "blue", tube: 1, order: 2 },
            { id: 11, color: "blue", tube: 2, order: 1 },
            { id: 12, color: "blue", tube: 3, order: 2 },
        ],
    },
    {
        tubeCount: 5,
        colorCount: 3,
        itemSet: [
            { id: 1, color: "red", tube: 1, order: 4 },
            { id: 2, color: "red", tube: 2, order: 3 },
            { id: 3, color: "red", tube: 1, order: 3 },
            { id: 4, color: "red", tube: 3, order: 2 },
            { id: 5, color: "green", tube: 1, order: 1 },
            { id: 6, color: "green", tube: 2, order: 4 },
            { id: 7, color: "green", tube: 3, order: 1 },
            { id: 8, color: "green", tube: 3, order: 4 },
            { id: 9, color: "blue", tube: 1, order: 3 },
            { id: 10, color: "blue", tube: 2, order: 2 },
            { id: 11, color: "blue", tube: 2, order: 1 },
            { id: 12, color: "blue", tube: 3, order: 3 },
        ],
    },
    {
        tubeCount: 6,
        colorCount: 4,
        itemSet: [
            { id: 1, color: "red", tube: 4, order: 3 },
            { id: 2, color: "red", tube: 2, order: 3 },
            { id: 3, color: "red", tube: 4, order: 2 },
            { id: 4, color: "red", tube: 4, order: 1 },
            { id: 5, color: "green", tube: 1, order: 1 },
            { id: 6, color: "green", tube: 4, order: 4 },
            { id: 7, color: "green", tube: 3, order: 2 },
            { id: 8, color: "green", tube: 3, order: 3 },
            { id: 9, color: "blue", tube: 1, order: 4 },
            { id: 10, color: "blue", tube: 1, order: 3 },
            { id: 11, color: "blue", tube: 1, order: 2 },
            { id: 12, color: "blue", tube: 2, order: 2 },
            { id: 13, color: "yellow", tube: 2, order: 4 },
            { id: 14, color: "yellow", tube: 2, order: 1 },
            { id: 15, color: "yellow", tube: 3, order: 4 },
            { id: 16, color: "yellow", tube: 3, order: 1 },
        ],
    },
    {
        tubeCount: 6,
        colorCount: 4,
        itemSet: [
            { id: 1, color: "red", tube: 4, order: 3 },
            { id: 2, color: "red", tube: 2, order: 2 },
            { id: 3, color: "red", tube: 1, order: 2 },
            { id: 4, color: "red", tube: 1, order: 3 },
            { id: 5, color: "green", tube: 1, order: 4 },
            { id: 6, color: "green", tube: 2, order: 4 },
            { id: 7, color: "green", tube: 3, order: 1 },
            { id: 8, color: "green", tube: 3, order: 3 },
            { id: 9, color: "blue", tube: 1, order: 1 },
            { id: 10, color: "blue", tube: 2, order: 3 },
            { id: 11, color: "blue", tube: 4, order: 4 },
            { id: 12, color: "blue", tube: 4, order: 1 },
            { id: 13, color: "yellow", tube: 2, order: 1 },
            { id: 14, color: "yellow", tube: 3, order: 2 },
            { id: 15, color: "yellow", tube: 3, order: 4 },
            { id: 16, color: "yellow", tube: 4, order: 2 },
        ],
    },
]